### ISSUE TITLE
You have stolen this plugin.

### ISSUE THREAD

**Issue by Vecnavium** [DanteDEVS/MurderMystery#2]
This plugin has been stolen, literal copy pasted plugin and provided 0 credits of the original author.
Original dev of this plugin is LeyKey.

**Comment by DevGod6969** [comment]
He did now

**Comment by DanteDEVS** [comment]
yeah i gave credits
in config.yml, readme.md and murdermystery.php

**Comment by DanteDEVS** [comment]
Gave credits = DONE
